name: Java UTAF Tests
 
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  workflow_dispatch:
jobs:
  UI_Test:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Set up Edge
        uses: browser-actions/setup-edge@latest
      - run: msedge --version

      # - name: Install and Run Appium Server
      #   uses: moatazeldebsy/appium-server-gitHub-action@V1.0.6

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Emulator Set-up
        uses: reactivecircus/android-emulator-runner@v2.30.1
        with:
          api-level: 34
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
       
      - name: Run tests with Maven
        run: mvn clean test
         
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
 
