name: Java UTAF Tests
 
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  workflow_dispatch:
jobs:
  UI_Test:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Set up Microsoft Edge
        uses: microsoft-edge/msedge-action@v1
        
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
       
      - name: Run tests with Maven
        run: mvn clean test
         
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
 
